import { MigrationInterface, QueryRunner } from "typeorm";

export class UpdateDatabase1736329354921 implements MigrationInterface {
    name = 'UpdateDatabase1736329354921'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`bank_transfer\` DROP FOREIGN KEY \`FK_8025937032b0c2d3b1b0c563f8a\``);
        await queryRunner.query(`ALTER TABLE \`voucher\` DROP FOREIGN KEY \`FK_e079f969220581b631c9123f27d\``);
        await queryRunner.query(`ALTER TABLE \`store\` DROP FOREIGN KEY \`FK_a83068090fe4511e5047484b09a\``);
        await queryRunner.query(`ALTER TABLE \`product\` DROP FOREIGN KEY \`FK_32eaa54ad96b26459158464379a\``);
        await queryRunner.query(`ALTER TABLE \`product\` DROP FOREIGN KEY \`FK_ff0c0301a95e517153df97f6812\``);
        await queryRunner.query(`ALTER TABLE \`order_item\` DROP FOREIGN KEY \`FK_646bf9ece6f45dbe41c203e06e0\``);
        await queryRunner.query(`ALTER TABLE \`order_item\` DROP FOREIGN KEY \`FK_904370c093ceea4369659a3c810\``);
        await queryRunner.query(`ALTER TABLE \`order\` DROP FOREIGN KEY \`FK_1a79b2f719ecd9f307d62b81093\``);
        await queryRunner.query(`ALTER TABLE \`order\` DROP FOREIGN KEY \`FK_caabe91507b3379c7ba73637b84\``);
        await queryRunner.query(`ALTER TABLE \`order\` DROP FOREIGN KEY \`FK_cff8eff4c72e7c4cb5bf045447c\``);
        await queryRunner.query(`ALTER TABLE \`transaction\` DROP FOREIGN KEY \`FK_a6e45c89cfbe8d92840266fd30f\``);
        await queryRunner.query(`ALTER TABLE \`transaction\` DROP FOREIGN KEY \`FK_f05df84c621b290c7e22ec529b8\``);
        await queryRunner.query(`ALTER TABLE \`transaction\` DROP FOREIGN KEY \`FK_f6204a9a4aabc1195fddcb3e917\``);
        await queryRunner.query(`DROP INDEX \`REL_a83068090fe4511e5047484b09\` ON \`store\``);
        await queryRunner.query(`ALTER TABLE \`store\` CHANGE \`ownerId\` \`userId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`bank_transfer\` CHANGE \`accountNumber\` \`accountNumber\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`bank_transfer\` CHANGE \`bankName\` \`bankName\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`bank_transfer\` DROP COLUMN \`transferAmount\``);
        await queryRunner.query(`ALTER TABLE \`bank_transfer\` ADD \`transferAmount\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`bank_transfer\` CHANGE \`transferDescription\` \`transferDescription\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`voucher\` DROP COLUMN \`voucherDiscount\``);
        await queryRunner.query(`ALTER TABLE \`voucher\` ADD \`voucherDiscount\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`store\` DROP COLUMN \`storeAddress\``);
        await queryRunner.query(`ALTER TABLE \`store\` ADD \`storeAddress\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`store\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`store\` ADD UNIQUE INDEX \`IDX_3f82dbf41ae837b8aa0a27d29c\` (\`userId\`)`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`email\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`email\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`displayName\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`displayName\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`avatar\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`avatar\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`phoneNumber\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`phoneNumber\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`role\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`role\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`password\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`password\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`refresh_token\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`refresh_token\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`product\` DROP COLUMN \`productPrice\``);
        await queryRunner.query(`ALTER TABLE \`product\` ADD \`productPrice\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`product\` CHANGE \`status\` \`status\` tinyint NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`product\` DROP COLUMN \`productImage\``);
        await queryRunner.query(`ALTER TABLE \`product\` ADD \`productImage\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`order_item\` DROP COLUMN \`unitPrice\``);
        await queryRunner.query(`ALTER TABLE \`order_item\` ADD \`unitPrice\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`order\` DROP COLUMN \`totalPrice\``);
        await queryRunner.query(`ALTER TABLE \`order\` ADD \`totalPrice\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`transaction\` DROP COLUMN \`transactionAmount\``);
        await queryRunner.query(`ALTER TABLE \`transaction\` ADD \`transactionAmount\` int NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_3f82dbf41ae837b8aa0a27d29c\` ON \`store\` (\`userId\`)`);
        await queryRunner.query(`ALTER TABLE \`bank_transfer\` ADD CONSTRAINT \`FK_8025937032b0c2d3b1b0c563f8a\` FOREIGN KEY (\`walletUserId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`voucher\` ADD CONSTRAINT \`FK_e079f969220581b631c9123f27d\` FOREIGN KEY (\`storeStoreId\`) REFERENCES \`store\`(\`storeId\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`store\` ADD CONSTRAINT \`FK_3f82dbf41ae837b8aa0a27d29c3\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product\` ADD CONSTRAINT \`FK_ff0c0301a95e517153df97f6812\` FOREIGN KEY (\`categoryId\`) REFERENCES \`category\`(\`categoryId\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product\` ADD CONSTRAINT \`FK_32eaa54ad96b26459158464379a\` FOREIGN KEY (\`storeId\`) REFERENCES \`store\`(\`storeId\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_item\` ADD CONSTRAINT \`FK_646bf9ece6f45dbe41c203e06e0\` FOREIGN KEY (\`orderId\`) REFERENCES \`order\`(\`orderId\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_item\` ADD CONSTRAINT \`FK_904370c093ceea4369659a3c810\` FOREIGN KEY (\`productId\`) REFERENCES \`product\`(\`productId\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order\` ADD CONSTRAINT \`FK_caabe91507b3379c7ba73637b84\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order\` ADD CONSTRAINT \`FK_1a79b2f719ecd9f307d62b81093\` FOREIGN KEY (\`storeId\`) REFERENCES \`store\`(\`storeId\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order\` ADD CONSTRAINT \`FK_cff8eff4c72e7c4cb5bf045447c\` FOREIGN KEY (\`voucherId\`) REFERENCES \`voucher\`(\`voucherId\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transaction\` ADD CONSTRAINT \`FK_a6e45c89cfbe8d92840266fd30f\` FOREIGN KEY (\`orderId\`) REFERENCES \`order\`(\`orderId\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transaction\` ADD CONSTRAINT \`FK_f05df84c621b290c7e22ec529b8\` FOREIGN KEY (\`transferUserId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transaction\` ADD CONSTRAINT \`FK_f6204a9a4aabc1195fddcb3e917\` FOREIGN KEY (\`receiveUserId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`transaction\` DROP FOREIGN KEY \`FK_f6204a9a4aabc1195fddcb3e917\``);
        await queryRunner.query(`ALTER TABLE \`transaction\` DROP FOREIGN KEY \`FK_f05df84c621b290c7e22ec529b8\``);
        await queryRunner.query(`ALTER TABLE \`transaction\` DROP FOREIGN KEY \`FK_a6e45c89cfbe8d92840266fd30f\``);
        await queryRunner.query(`ALTER TABLE \`order\` DROP FOREIGN KEY \`FK_cff8eff4c72e7c4cb5bf045447c\``);
        await queryRunner.query(`ALTER TABLE \`order\` DROP FOREIGN KEY \`FK_1a79b2f719ecd9f307d62b81093\``);
        await queryRunner.query(`ALTER TABLE \`order\` DROP FOREIGN KEY \`FK_caabe91507b3379c7ba73637b84\``);
        await queryRunner.query(`ALTER TABLE \`order_item\` DROP FOREIGN KEY \`FK_904370c093ceea4369659a3c810\``);
        await queryRunner.query(`ALTER TABLE \`order_item\` DROP FOREIGN KEY \`FK_646bf9ece6f45dbe41c203e06e0\``);
        await queryRunner.query(`ALTER TABLE \`product\` DROP FOREIGN KEY \`FK_32eaa54ad96b26459158464379a\``);
        await queryRunner.query(`ALTER TABLE \`product\` DROP FOREIGN KEY \`FK_ff0c0301a95e517153df97f6812\``);
        await queryRunner.query(`ALTER TABLE \`store\` DROP FOREIGN KEY \`FK_3f82dbf41ae837b8aa0a27d29c3\``);
        await queryRunner.query(`ALTER TABLE \`voucher\` DROP FOREIGN KEY \`FK_e079f969220581b631c9123f27d\``);
        await queryRunner.query(`ALTER TABLE \`bank_transfer\` DROP FOREIGN KEY \`FK_8025937032b0c2d3b1b0c563f8a\``);
        await queryRunner.query(`DROP INDEX \`REL_3f82dbf41ae837b8aa0a27d29c\` ON \`store\``);
        await queryRunner.query(`ALTER TABLE \`transaction\` DROP COLUMN \`transactionAmount\``);
        await queryRunner.query(`ALTER TABLE \`transaction\` ADD \`transactionAmount\` decimal NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`order\` DROP COLUMN \`totalPrice\``);
        await queryRunner.query(`ALTER TABLE \`order\` ADD \`totalPrice\` decimal NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`order_item\` DROP COLUMN \`unitPrice\``);
        await queryRunner.query(`ALTER TABLE \`order_item\` ADD \`unitPrice\` decimal NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`product\` DROP COLUMN \`productImage\``);
        await queryRunner.query(`ALTER TABLE \`product\` ADD \`productImage\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`product\` CHANGE \`status\` \`status\` tinyint NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`product\` DROP COLUMN \`productPrice\``);
        await queryRunner.query(`ALTER TABLE \`product\` ADD \`productPrice\` decimal NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`refresh_token\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`refresh_token\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`password\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`password\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`role\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`role\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`phoneNumber\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`phoneNumber\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`avatar\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`avatar\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`displayName\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`displayName\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`email\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`email\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`store\` DROP INDEX \`IDX_3f82dbf41ae837b8aa0a27d29c\``);
        await queryRunner.query(`ALTER TABLE \`store\` CHANGE \`userId\` \`userId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`store\` DROP COLUMN \`storeAddress\``);
        await queryRunner.query(`ALTER TABLE \`store\` ADD \`storeAddress\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`voucher\` DROP COLUMN \`voucherDiscount\``);
        await queryRunner.query(`ALTER TABLE \`voucher\` ADD \`voucherDiscount\` decimal NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`bank_transfer\` CHANGE \`transferDescription\` \`transferDescription\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`bank_transfer\` DROP COLUMN \`transferAmount\``);
        await queryRunner.query(`ALTER TABLE \`bank_transfer\` ADD \`transferAmount\` decimal NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`bank_transfer\` CHANGE \`bankName\` \`bankName\` varchar(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`bank_transfer\` CHANGE \`accountNumber\` \`accountNumber\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`store\` CHANGE \`userId\` \`ownerId\` int NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_a83068090fe4511e5047484b09\` ON \`store\` (\`ownerId\`)`);
        await queryRunner.query(`ALTER TABLE \`transaction\` ADD CONSTRAINT \`FK_f6204a9a4aabc1195fddcb3e917\` FOREIGN KEY (\`receiveUserId\`) REFERENCES \`sep490_ftopwallet\`.\`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transaction\` ADD CONSTRAINT \`FK_f05df84c621b290c7e22ec529b8\` FOREIGN KEY (\`transferUserId\`) REFERENCES \`sep490_ftopwallet\`.\`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transaction\` ADD CONSTRAINT \`FK_a6e45c89cfbe8d92840266fd30f\` FOREIGN KEY (\`orderId\`) REFERENCES \`sep490_ftopwallet\`.\`order\`(\`orderId\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order\` ADD CONSTRAINT \`FK_cff8eff4c72e7c4cb5bf045447c\` FOREIGN KEY (\`voucherId\`) REFERENCES \`sep490_ftopwallet\`.\`voucher\`(\`voucherId\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order\` ADD CONSTRAINT \`FK_caabe91507b3379c7ba73637b84\` FOREIGN KEY (\`userId\`) REFERENCES \`sep490_ftopwallet\`.\`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order\` ADD CONSTRAINT \`FK_1a79b2f719ecd9f307d62b81093\` FOREIGN KEY (\`storeId\`) REFERENCES \`sep490_ftopwallet\`.\`store\`(\`storeId\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_item\` ADD CONSTRAINT \`FK_904370c093ceea4369659a3c810\` FOREIGN KEY (\`productId\`) REFERENCES \`sep490_ftopwallet\`.\`product\`(\`productId\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_item\` ADD CONSTRAINT \`FK_646bf9ece6f45dbe41c203e06e0\` FOREIGN KEY (\`orderId\`) REFERENCES \`sep490_ftopwallet\`.\`order\`(\`orderId\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product\` ADD CONSTRAINT \`FK_ff0c0301a95e517153df97f6812\` FOREIGN KEY (\`categoryId\`) REFERENCES \`sep490_ftopwallet\`.\`category\`(\`categoryId\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product\` ADD CONSTRAINT \`FK_32eaa54ad96b26459158464379a\` FOREIGN KEY (\`storeId\`) REFERENCES \`sep490_ftopwallet\`.\`store\`(\`storeId\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`store\` ADD CONSTRAINT \`FK_a83068090fe4511e5047484b09a\` FOREIGN KEY (\`ownerId\`) REFERENCES \`sep490_ftopwallet\`.\`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`voucher\` ADD CONSTRAINT \`FK_e079f969220581b631c9123f27d\` FOREIGN KEY (\`storeStoreId\`) REFERENCES \`sep490_ftopwallet\`.\`store\`(\`storeId\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`bank_transfer\` ADD CONSTRAINT \`FK_8025937032b0c2d3b1b0c563f8a\` FOREIGN KEY (\`walletUserId\`) REFERENCES \`sep490_ftopwallet\`.\`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
